### PR TITLE
rename the package to com.android.dx instead of using jarjar

### LINKED ISSUE #18: Unable to run tests with Android and 1.3
Hello,
I'm trying to use version 1.3 (from central repository) with Android and Mockito but I am getting the following error:
Caused by: java.lang.NoClassDefFoundError: com.google.dexmaker.dx.rop.type.Type

I also tried to import also dexmaker-dx 1.3 but it doesn't solve the issue because the package of the included classes is different (com.android.dx instead of com.google.dexmaker.dx).

The only way I've found to make it work is to build v1.3 manually and then include the **original-dexmaker-1.3** , dexmaker-dx-1.3 and dexmaker-mockito-1.3 jars in my project.
What's the difference between dexmaker and original-dexmaker? Is there a way to make things work by downloading jars from the central repository instead of including them manually?

### PR DESCRIPTION
**Pull request by ened**
Fixes #18 for me.

For local tests, check out this repository & branch, then run `mvn clean install -Dgpg.skip=true`. 
In a your project you need to refer to the local maven cache directory and use `1.4-SNAPSHOT` as the version.

### CODE REVIEW

**Comment by vaughandroid** [comment]
@ened Could you explain what's going on here please?
From what I can tell, the jarjar mapping you removed was mapping packages from `com.android.dx.XXX` to `com.google.dexmaker.dx.XXX`. Your manual package change moves some classes from `com.google.dexmaker.XXX` to `com.android.dx`. How does this fix the `NoClassDefFoundError` problems (per #18)?

**Comment by ened** [comment]
Ok, there is repackaging going on only for the dexmaker module, not for the dx module, however, the dexmaker classes refer to `dx` classes. 
Using jarjar therefore fixes only the front-facing components, not the underlying components.

Also, using jarjar for for both dexmaker and dx won't help as there is still a cross reference (import) and the only way to fix that one is to remove the repackaging and make everything work with the target package name.

**Comment by dshirley** [comment]
LGTM

**Comment by dshirley** [comment]
Pushed this out as v1.4

**Comment by vaughandroid** [comment]
Woohoo! Thanks @dshirley and @ened both. :+1:

**Comment by paulduffin** [comment]
I may be missing something obvious but it seems to me as though this does not fix #18. Certainly, it seems from looking at #18, that the problem was much simpler and was just a missing dependency on dexmaker-dx.

What this does do is completely change the public API of dexmaker and break all direct clients of dexmaker. It's use in Mockito is the only usage that won't be affected. Whereas before I had code that called say com.google.dexmaker.stock.ProxyBuilder, now I have to change the code to call com.android.dx.stock.ProxyBuilder.

It also creates overlapping packages between dexmaker and dexmaker-dx artifacts with the potential for build/runtime problems if they end up with a class with the same name.

I think that this change was a mistake, could you revert it please? I'm happy to create a new pull request if that helps.

**Pull request merged**
